import Head from "next/head";
import Navbar from "../../componants/Navbar";
import { Button, Text } from "@mantine/core";
import StudentTable from "../../componants/StudentTable";
import { useState } from "react";
import NewStudent from "../../componants/NewStudent";
export default function Home() {
  const [opened, setOpened] = useState(false);
  return (
    <div
      style={{
        minWidth: "100vw",
        minHeight: "100vh",
        backgroundImage:
          "linear-gradient(135deg, rgba(186, 186, 186, 0.03) 0%, rgba(186, 186, 186, 0.03) 10%,rgba(133, 133, 133, 0.03) 10%, rgba(133, 133, 133, 0.03) 14%,rgba(38, 38, 38, 0.03) 14%, rgba(38, 38, 38, 0.03) 17%,rgba(93, 93, 93, 0.03) 17%, rgba(93, 93, 93, 0.03) 25%,rgba(80, 80, 80, 0.03) 25%, rgba(80, 80, 80, 0.03) 45%,rgba(239, 239, 239, 0.03) 45%, rgba(239, 239, 239, 0.03) 100%),linear-gradient(135deg, rgba(236, 236, 236, 0.03) 0%, rgba(236, 236, 236, 0.03) 47%,rgba(182, 182, 182, 0.03) 47%, rgba(182, 182, 182, 0.03) 63%,rgba(223, 223, 223, 0.03) 63%, rgba(223, 223, 223, 0.03) 81%,rgba(86, 86, 86, 0.03) 81%, rgba(86, 86, 86, 0.03) 89%,rgba(23, 23, 23, 0.03) 89%, rgba(23, 23, 23, 0.03) 90%,rgba(226, 226, 226, 0.03) 90%, rgba(226, 226, 226, 0.03) 100%),linear-gradient(45deg, rgba(52, 52, 52, 0.03) 0%, rgba(52, 52, 52, 0.03) 31%,rgba(246, 246, 246, 0.03) 31%, rgba(246, 246, 246, 0.03) 63%,rgba(188, 188, 188, 0.03) 63%, rgba(188, 188, 188, 0.03) 71%,rgba(15, 15, 15, 0.03) 71%, rgba(15, 15, 15, 0.03) 87%,rgba(127, 127, 127, 0.03) 87%, rgba(127, 127, 127, 0.03) 93%,rgba(234, 234, 234, 0.03) 93%, rgba(234, 234, 234, 0.03) 100%),linear-gradient(90deg, #ffffff,#ffffff)",
      }}
    >
      <Head>
        <title>CSE - Present Sir</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <Navbar />

      <div
        style={{
          marginLeft: 200,
          borderRadius: "15px",
          backgroundColor: "rgba(204, 237, 255, 0.4)",
          padding: "20px",
          width: "30%",
        }}
      >
        <Text size="xl">Computer Graphics</Text>
        <Text size="lg">CSE373</Text>
        <Text size="md">2018-19</Text>
        <Text size="sm">Total Class : 15</Text>
        <Text size="sm">Total Student : 108</Text>
      </div>
      <div style={{ display: "flex", justifyContent: "space-evenly" }}>
        <div>
          <Button
            variant="gradient"
            gradient={{ from: "indigo", to: "cyan" }}
            onClick={() => {
              setOpened(true);
            }}
          >
            Add Student
          </Button>
          <Button
            variant="gradient"
            gradient={{ from: "teal", to: "lime", deg: 105 }}
            sx={{ margin: 20 }}
          >
            Import From CSV
          </Button>
        </div>
        <Button
          variant="gradient"
          size="xl"
          gradient={{ from: "teal", to: "blue" }}
        >
          Take Attendance
        </Button>
        <div>
          <Button variant="gradient" gradient={{ from: "orange", to: "red" }}>
            Export As CSV
          </Button>
          <Button
            variant="gradient"
            gradient={{ from: "#ed6ea0", to: "#ec8c69", deg: 35 }}
            sx={{ margin: 20 }}
          >
            Export As PDF
          </Button>
        </div>
      </div>
      <div style={{ marginLeft: 100, marginRight: 100 }}>
        <StudentTable />
      </div>
      <NewStudent opened={opened} setOpened={setOpened} />
    </div>
  );
}
